$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $PSScriptRoot
$IncludeDir = Join-Path $Root "include"
$Entry = Join-Path $IncludeDir "cp_stress_gen.hpp"
$DistDir = Join-Path $Root "dist"
$Output = Join-Path $DistDir "cp_stress_gen.hpp"

New-Item -ItemType Directory -Force $DistDir | Out-Null

$SeenProjectHeaders = New-Object "System.Collections.Generic.HashSet[string]"
$StandardIncludes = New-Object "System.Collections.Generic.SortedSet[string]"
$IncludeRootFull = [System.IO.Path]::GetFullPath($IncludeDir)

function Resolve-Project-Include {
    param(
        [string]$CurrentHeader,
        [string]$IncludePath
    )

    $CurrentDir = Split-Path -Parent $CurrentHeader
    $Candidate = [System.IO.Path]::GetFullPath((Join-Path $CurrentDir $IncludePath))
    if (-not $Candidate.StartsWith($IncludeRootFull, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Project include escapes include directory: $IncludePath"
    }
    if (-not (Test-Path $Candidate)) {
        throw "Project include not found: $IncludePath"
    }
    return $Candidate
}

function Expand-Header {
    param([string]$HeaderPath)

    $FullPath = [System.IO.Path]::GetFullPath($HeaderPath)
    if (-not $SeenProjectHeaders.Add($FullPath)) {
        return New-Object "System.Collections.Generic.List[string]"
    }

    $Expanded = New-Object "System.Collections.Generic.List[string]"
    $Relative = $FullPath.Substring($IncludeRootFull.Length).TrimStart("\", "/").Replace("\", "/")
    $Expanded.Add("// BEGIN: include/$Relative")

    foreach ($Line in [System.IO.File]::ReadAllLines($FullPath)) {
        if ($Line -match '^\s*#pragma once\s*$') {
            continue
        }

        if ($Line -match '^\s*#include\s+<([^>]+)>\s*$') {
            [void]$StandardIncludes.Add("#include <$($Matches[1])>")
            continue
        }

        if ($Line -match '^\s*#include\s+"([^"]+)"\s*$') {
            $Included = Resolve-Project-Include $FullPath $Matches[1]
            $Nested = Expand-Header $Included
            foreach ($NestedLine in $Nested) {
                $Expanded.Add($NestedLine)
            }
            continue
        }

        $Expanded.Add($Line)
    }

    $Expanded.Add("// END: include/$Relative")
    $Expanded.Add("")
    return $Expanded
}

$Body = Expand-Header $Entry
$Lines = New-Object "System.Collections.Generic.List[string]"
$Lines.Add("// CP-Stress-Gen single-header bundle")
$Lines.Add("// SPDX-License-Identifier: MIT")
$Lines.Add("// Generated from include/ by scripts/bundle_single_header.ps1.")
$Lines.Add("// Do not edit this file manually; edit headers under include/ instead.")
$Lines.Add("// Requires C++17 or newer.")
$Lines.Add("#pragma once")
$Lines.Add("")
foreach ($Include in $StandardIncludes) {
    $Lines.Add($Include)
}
$Lines.Add("")
foreach ($Line in $Body) {
    $Lines.Add($Line)
}

[System.IO.File]::WriteAllText($Output, (($Lines -join "`r`n") + "`r`n"), [System.Text.UTF8Encoding]::new($false))
Write-Host "[PASS] bundle_single_header $Output"
