$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $PSScriptRoot
$IncludeDir = Join-Path $Root "include"
$Entry = Join-Path $IncludeDir "cp_stress_gen.hpp"
$DistDir = Join-Path $Root "dist"
$Output = Join-Path $DistDir "cp_stress_gen.hpp"

New-Item -ItemType Directory -Force $DistDir | Out-Null

$SeenProjectHeaders = New-Object "System.Collections.Generic.HashSet[string]"
$StandardIncludes = New-Object "System.Collections.Generic.SortedSet[string]"
$IncludeRootFull = [System.IO.Path]::GetFullPath($IncludeDir)

function Resolve-Project-Include {
    param(
        [string]$CurrentHeader,
        [string]$IncludePath
    )

    $CurrentDir = Split-Path -Parent $CurrentHeader
    $Candidate = [System.IO.Path]::GetFullPath((Join-Path $CurrentDir $IncludePath))
    $InsideIncludeRoot = $Candidate.StartsWith(
        $IncludeRootFull,
        [System.StringComparison]::OrdinalIgnoreCase
    )
    if (-not $InsideIncludeRoot) {
        throw "Project include escapes include directory: $IncludePath"
    }
    if (-not (Test-Path $Candidate)) {
        throw "Project include not found: $IncludePath"
    }
    return $Candidate
}

function Expand-Header {
    param([string]$HeaderPath)

    $FullPath = [System.IO.Path]::GetFullPath($HeaderPath)
    if (-not $SeenProjectHeaders.Add($FullPath)) {
        return New-Object "System.Collections.Generic.List[string]"
    }

    $Expanded = New-Object "System.Collections.Generic.List[string]"
    $Relative = $FullPath.Substring($IncludeRootFull.Length)
    $Relative = $Relative.TrimStart("\", "/").Replace("\", "/")
    $Expanded.Add("// BEGIN: include/$Relative")

    foreach ($Line in [System.IO.File]::ReadAllLines($FullPath)) {
        if ($Line -match '^\s*#pragma once\s*$') {
            continue
        }

        if ($Line -match '^\s*#include\s+<([^>]+)>\s*$') {
            [void]$StandardIncludes.Add("#include <$($Matches[1])>")
            continue
        }

        if ($Line -match '^\s*#include\s+"([^"]+)"\s*$') {
            $Included = Resolve-Project-Include $FullPath $Matches[1]
            $Nested = Expand-Header $Included
            foreach ($NestedLine in $Nested) {
                $Expanded.Add($NestedLine)
            }
            continue
        }

        $Expanded.Add($Line)
    }

    $Expanded.Add("// END: include/$Relative")
    $Expanded.Add("")
    return $Expanded
}

$Body = Expand-Header $Entry
if ($Body.Count -lt 500) {
    throw "Generated bundle is unexpectedly small; local headers may not have been expanded."
}

$BodyText = $Body -join "`n"
if ($BodyText -notmatch "namespace\s+cp_stress_gen") {
    throw "Generated bundle does not appear to contain CP-Stress-Gen library code."
}

$Lines = New-Object "System.Collections.Generic.List[string]"
$Lines.Add("// CP-Stress-Gen single-header bundle")
$Lines.Add("// SPDX-License-Identifier: MIT")
$Lines.Add("// Generated from include/ by scripts/bundle_single_header.ps1.")
$Lines.Add("// Do not edit this file manually; edit headers under include/ instead.")
$Lines.Add("// Requires C++17 or newer.")
$Lines.Add("#pragma once")
$Lines.Add("")
foreach ($Include in $StandardIncludes) {
    $Lines.Add($Include)
}
$Lines.Add("")
foreach ($Line in $Body) {
    $Lines.Add($Line)
}

$QuotedProjectIncludes = $Lines | Where-Object {
    $_ -match '^\s*#include\s+"'
}
if ($QuotedProjectIncludes.Count -gt 0) {
    throw "Generated bundle still contains quoted project includes."
}

$OutputText = ($Lines -join "`r`n") + "`r`n"
$Utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($Output, $OutputText, $Utf8NoBom)
Write-Host "[PASS] bundle_single_header $Output"
